StylesPath = .vale/styles
MinAlertLevel = warning

Vocab = IS

[*.md]
BasedOnStyles = Vale

# Skip YAML frontmatter — Vale doesn't parse it
TokenIgnores = (?s)(^---\n.*?\n---\n)
BlockIgnores = (?s) *(```.*?```)
