StylesPath = .vale/styles
MinAlertLevel = warning
Packages = Microsoft

Vocab = IS

[*.md]
BasedOnStyles = Vale, Microsoft, IS

# Skip YAML frontmatter — Vale doesn't parse it
TokenIgnores = (?s)(^---\n.*?\n---\n)
BlockIgnores = (?s) *(```.*?```)
